let userage = 19;
let birth = 2004;
let year = new Date().getFullYear();
console.log("Yes is age is ",age)
if (birth - year == userage){
    console.log("Yes is age is ",userage)
}


const currentDate = moment().format("YYYY/MM/DD");
console.log(currentDate);

let user = {
    name:"na",
    age:20,
    email:"narudom@gmail.com"
};
let product = {name:"มะม่วง",
price:150,
categor:"ผลไม้"
};
console.log(product.name)
